version: 2.1

executors:
  ubuntu:
    docker:
      - image: ubuntu:20.04

jobs:
  build:
    executor: ubuntu
    steps:
      - run:
          name: Install packages
          command: |
            apt update
            apt install -y git make docker.io
      - checkout
      - setup_remote_docker:
          # We might want to add this when things get slow
          # https://circleci.com/docs/2.0/docker-layer-caching/
          docker_layer_caching: false
      - run:
          name: Build Docker artifact
          command: make build
  lint-scripts:
    executor: ubuntu
    steps:
      - run:
          name: Install packages
          command: |
            apt update
            apt install -y git shellcheck
      - checkout
      - run:
          name: Run shellcheck
          command: find . -name "*.sh" -exec shellcheck {} +
  format-scripts:
    docker:
      - image: cimg/go:1.16.3
    steps:
      - run:
          name: Install shfmt
          command: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      - checkout
      - run:
          name: Run shfmt
          command: shfmt -d .

workflows:
  version: 2
  test-suite:
    jobs:
      - build
      - lint-scripts
      - format-scripts
